# -*- coding: utf-8 -*-
"""
Fuente de verdad de la carta de El Bigote Coffee & Waffles.

Transcrita de las imágenes oficiales de la carta (carpeta Carta-Menu).
La traducción al inglés se hizo sobre esos mismos textos.

Editar AQUÍ y después ejecutar:  python3 tools/generar_carta.py
Eso regenera el bloque de la carta dentro de index.html y data/carta.json.

Formato de cada plato:
    (nombre_es, nombre_en, precio, descripcion_es, descripcion_en, etiquetas)

- precio: cadena tal cual se imprime ("14", "6.5 – 8.5", "9"). None = sin precio.
- etiquetas: lista opcional. "top" = el más pedido · "veg" = sin carne
"""

CATEGORIAS = [
  # ─────────────────────────── WAFFLES DULCES ───────────────────────────
  dict(id="waffles-dulces", cat="waffles dulce",
       es="Waffles dulces", en="Sweet waffles",
       nota_es=None, nota_en=None,
       items=[
    ("Original", "Original", "14",
     "Waffle con miel de abeja o maple o manjar blanco o salsa de chocolate.",
     "Waffle with honey, maple syrup, dulce de leche or chocolate sauce.", []),
    ("Encanelado", "Cinnamon", "17",
     "Canela, salsa de canela y glaseado de queso crema.",
     "Cinnamon, cinnamon sauce and cream cheese glaze.", []),
    ("Tres leches", "Tres leches", "19",
     "Waffle relleno de una deliciosa salsa tres leches. Acompañado de manjar blanco y crema chantilly.",
     "Waffle filled with tres leches sauce, served with dulce de leche and whipped cream.", ["top"]),
    ("Frutas frescas", "Fresh fruit", "18",
     "Frutas de la estación con miel de maple o miel de abeja o crema pastelera.",
     "Seasonal fruit with maple syrup, honey or pastry cream.", []),
    ("Caramel banana", "Caramel banana", "19",
     "Plátano, salsa de canela, mix de nueces, salsa de chocolate, crema pastelera, brownie bites.",
     "Banana, cinnamon sauce, mixed nuts, chocolate sauce, pastry cream and brownie bites.", []),
    ("Del bosque", "Forest berries", "21",
     "Fresas, arándanos, crema pastelera y mermelada de frutos rojos.",
     "Strawberries, blueberries, pastry cream and red berry jam.", []),
    ("Cheesecake tropical", "Tropical cheesecake", "20",
     "Waffle con glaseado de queso crema, coulis de mango, piña y menta, crumble, mango y piña.",
     "Waffle with cream cheese glaze, mango coulis, pineapple and mint, crumble, mango and pineapple.", []),
    ("Tartaleta de fresa", "Strawberry tart", "20",
     "Fresas, crema pastelera, crumble y mermelada de fresa.",
     "Strawberries, pastry cream, crumble and strawberry jam.", []),
    ("Cheesecake de maracumango", "Passion fruit & mango cheesecake", "17",
     "Waffle con glaseado de queso crema, coulis de maracumango, mango y crumble.",
     "Waffle with cream cheese glaze, passion fruit and mango coulis, mango and crumble.", []),
    ("Cheesecake de frutos rojos", "Red berry cheesecake", "21",
     "Waffle con glaseado de queso crema, mermelada de frutos rojos, arándanos, fresas y crumble.",
     "Waffle with cream cheese glaze, red berry jam, blueberries, strawberries and crumble.", []),
    ("Arma tu waffle", "Build your own waffle", "24",
     "Escoge 5 toppings: fresas, arándanos, plátano, aguaymanto, mango, piña, manzana acaramelada, "
     "crumble, manjar blanco, salsa de chocolate, leche condensada, miel de abeja o de maple, "
     "crema pastelera o chantilly, crema de avellanas, brownie bites, mermelada de frutos rojos o de fresa, "
     "coulis de maracumango, chispas de chocolate, mix de nueces.",
     "Pick 5 toppings: strawberries, blueberries, banana, goldenberry, mango, pineapple, caramelised apple, "
     "crumble, dulce de leche, chocolate sauce, condensed milk, honey or maple syrup, "
     "pastry or whipped cream, hazelnut spread, brownie bites, red berry or strawberry jam, "
     "passion fruit and mango coulis, chocolate chips, mixed nuts.", []),
  ]),

  # ─────────────────────────── WAFFLES SALADOS ───────────────────────────
  dict(id="waffles-salados", cat="waffles salado",
       es="Waffles salados", en="Savoury waffles",
       nota_es="Acompaña tu waffle con ensalada o papas chips. Adicionales: tocino, huevo, queso, jamón, palta o papas chips +4.",
       nota_en="Served with salad or crisps. Extras: bacon, egg, cheese, ham, avocado or crisps +4.",
       items=[
    ("Popeye", "Popeye", "17",
     "Waffle relleno de espinaca, tocino y queso + mayonesa Bigote.",
     "Waffle filled with spinach, bacon and cheese + house Bigote mayo.", []),
    ("Champipollo", "Champipollo", "23",
     "Champiñones, crema de leche y especias.",
     "Chicken with mushrooms, cream and spices.", ["top"]),
    ("Tejano", "Tejano", "24",
     "Waffle relleno de lomito ahumado, chorizo, bondiola y coronado con queso cheddar y un huevo frito + salsa BBQ.",
     "Waffle filled with smoked pork loin, chorizo and pork shoulder, topped with cheddar and a fried egg + BBQ sauce.", ["top"]),
    ("Americano", "American", "19",
     "Waffle original, tocino, huevos a tu gusto, miel de maple.",
     "Original waffle, bacon, eggs your way and maple syrup.", []),
    ("Mixto a la inglesa", "English mixto", "19",
     "Waffle relleno de jamón, queso, orégano y coronado con un huevo frito + mayonesa Bigote.",
     "Waffle filled with ham, cheese and oregano, topped with a fried egg + house Bigote mayo.", []),
    ("Waffle pollo BBQ", "BBQ chicken waffle", "23",
     "Waffle sándwich con filete de pollo a la plancha, salsa BBQ, queso cheddar, tocino, tomate y lechuga.",
     "Waffle sandwich with grilled chicken fillet, BBQ sauce, cheddar, bacon, tomato and lettuce.", []),
    ("Club sándwich", "Club sandwich", "26",
     "Waffle sándwich con pollo deshilachado, jamón, queso andino, palta, tocino, huevo, tomate, lechuga y mayonesa.",
     "Waffle sandwich with pulled chicken, ham, Andean cheese, avocado, bacon, egg, tomato, lettuce and mayo.", []),
    ("Waffle pollo crispy", "Crispy chicken waffle", "25",
     "Waffle sándwich con pollo empanizado, queso cheddar, tocino, mayonesa Bigote, tomate y lechuga.",
     "Waffle sandwich with breaded chicken, cheddar, bacon, house Bigote mayo, tomato and lettuce.", []),
    ("Waffle burger", "Waffle burger", "23",
     "Waffle sándwich con hamburguesa de la casa, tocino, queso cheddar, tomate y lechuga.",
     "Waffle sandwich with our house burger, bacon, cheddar, tomato and lettuce.", []),
  ]),

  # ─────────────────────────── WAFFLES CON HELADO ───────────────────────────
  dict(id="waffles-helado", cat="waffles dulce",
       es="Waffles con helado", en="Waffles with ice cream",
       nota_es="Sabores de helado: chocolate, vainilla, fresa, cookies and cream o lúcuma. "
               "Adicionales: miel, salsa de chocolate, manjar o crema +3 · fruta, mix de nueces, brownie o manzanas +4 · "
               "crema de avellanas +5 · bola de helado +6.",
       nota_en="Ice cream flavours: chocolate, vanilla, strawberry, cookies and cream or lúcuma. "
               "Extras: honey, chocolate sauce, dulce de leche or cream +3 · fruit, mixed nuts, brownie or apples +4 · "
               "hazelnut spread +5 · scoop of ice cream +6.",
       items=[
    ("Applewaffle", "Applewaffle", "22",
     "Manzanas acarameladas, crema pastelera, crumble, canela y helado artesanal.",
     "Caramelised apples, pastry cream, crumble, cinnamon and artisan ice cream.", []),
    ("Avellanas", "Hazelnut", "24",
     "Fresas, plátano, crema de avellanas y helado artesanal.",
     "Strawberries, banana, hazelnut spread and artisan ice cream.", []),
    ("Berry waffle", "Berry waffle", "22",
     "Arándanos en la masa, miel de maple, crema chantilly y helado artesanal.",
     "Blueberries in the batter, maple syrup, whipped cream and artisan ice cream.", []),
    ("Waffle tiramisú", "Tiramisu waffle", "21",
     "Waffle con sabor a café, glaseado de queso crema, cobertura de chocolate rallado y helado artesanal.",
     "Coffee-flavoured waffle, cream cheese glaze, grated chocolate and artisan ice cream.", []),
    ("Chocoloco", "Chocoloco", "21",
     "Chispas de chocolate en la masa, crema chantilly, salsa de chocolate, brownie bites y helado artesanal.",
     "Chocolate chips in the batter, whipped cream, chocolate sauce, brownie bites and artisan ice cream.", []),
    ("Waffle Bigote", "Bigote waffle", "24",
     "Crema de avellanas, brownie bites, salsa de chocolate y helado artesanal.",
     "Hazelnut spread, brownie bites, chocolate sauce and artisan ice cream.", ["top"]),
    ("Cookies n' cream", "Cookies n' cream", "21",
     "Galletas oreo, salsa de chocolate, crema chantilly y helado artesanal.",
     "Oreo cookies, chocolate sauce, whipped cream and artisan ice cream.", []),
    ("Red velvet", "Red velvet", "21",
     "Inspirado en la famosa torta red velvet, con glaseado de queso crema, arándanos, mix de nueces y helado artesanal.",
     "Inspired by the classic red velvet cake: cream cheese glaze, blueberries, mixed nuts and artisan ice cream.", []),
    ("Dark waffle", "Dark waffle", "21",
     "Masa de chocolate, fresas, arándanos, crema chantilly, salsa de chocolate y helado artesanal.",
     "Chocolate batter, strawberries, blueberries, whipped cream, chocolate sauce and artisan ice cream.", []),
    ("Popular", "Popular", "28",
     "Crema de avellanas, fresas, brownie bites, salsa de chocolate o miel de maple y helado artesanal.",
     "Hazelnut spread, strawberries, brownie bites, chocolate sauce or maple syrup and artisan ice cream.", []),
    ("Banana split", "Banana split", "21",
     "Plátano, salsa de chocolate, crema chantilly y helado artesanal.",
     "Banana, chocolate sauce, whipped cream and artisan ice cream.", []),
  ]),

  # ─────────────────────────── DESAYUNOS ───────────────────────────
  dict(id="desayunos", cat="desayuno",
       es="Desayunos y brunch", en="Breakfast & brunch",
       nota_es="Disponibles hasta la 1 p.m. Incluyen café americano o espresso. "
               "Cambia tu café por cappuccino +2, infusión Bigote +2 o chocolate caliente +3. "
               "Jugo de naranja en lugar del jugo del día +2.5. Porción de pan 3 · porción de mantequilla 3.",
       nota_en="Served until 1 p.m. Includes americano or espresso. "
               "Swap your coffee for cappuccino +2, Bigote herbal tea +2 or hot chocolate +3. "
               "Orange juice instead of juice of the day +2.5. Bread 3 · butter 3.",
       items=[
    ("El Bigote", "El Bigote", "27",
     "Waffle original, 2 huevos, tocino, café y jugo del día.",
     "Original waffle, 2 eggs, bacon, coffee and juice of the day.", ["top"]),
    ("El apaltado", "The avocado one", "23",
     "Pan tostado, palta, tomate, 2 huevos, café y jugo del día.",
     "Toast, avocado, tomato, 2 eggs, coffee and juice of the day.", []),
    ("El light", "The light one", "18",
     "3 huevos, pan tostado, café y jugo del día.",
     "3 eggs, toast, coffee and juice of the day.", []),
    ("El frutal", "The fruity one", "28",
     "Ensalada de frutas, 2 huevos, pan tostado y café.",
     "Fruit salad, 2 eggs, toast and coffee.", []),
    ("Desayuno mixto a la inglesa", "English mixto breakfast", "23",
     "Waffle relleno de jamón, queso y orégano, acompañado de un huevo frito, café y jugo del día.",
     "Waffle filled with ham, cheese and oregano, with a fried egg, coffee and juice of the day.", []),
    ("Desayuno completo", "Full breakfast", "33",
     "Waffle original, 2 huevos, tocino, mini bowl de frutas, café y jugo del día.",
     "Original waffle, 2 eggs, bacon, a small fruit bowl, coffee and juice of the day.", []),
    ("El capresse", "The caprese one", "18",
     "Sándwich capresse, café y jugo del día.",
     "Caprese sandwich, coffee and juice of the day.", ["veg"]),
    ("Los revoltosos · jamón", "Scrambled eggs · ham", "15",
     "Pan tostado y huevos revueltos con jamón.",
     "Toast and scrambled eggs with ham.", []),
    ("Los revoltosos · espinaca y mozzarella", "Scrambled eggs · spinach & mozzarella", "17",
     "Pan tostado y huevos revueltos con espinaca y queso mozzarella.",
     "Toast and scrambled eggs with spinach and mozzarella.", ["veg"]),
    ("Los revoltosos · chorizo o tocino", "Scrambled eggs · chorizo or bacon", "17",
     "Pan tostado y huevos revueltos con chorizo o tocino.",
     "Toast and scrambled eggs with chorizo or bacon.", []),
    ("Los revoltosos · albahaca, tomate y mozzarella", "Scrambled eggs · basil, tomato & mozzarella", "17",
     "Pan tostado y huevos revueltos con albahaca, tomate y queso mozzarella.",
     "Toast and scrambled eggs with basil, tomato and mozzarella.", ["veg"]),
    ("Ensalada de frutas", "Fruit salad", "18",
     "Frutas de la estación, granola y miel de abeja.",
     "Seasonal fruit, granola and honey.", ["veg"]),
  ]),
]

CATEGORIAS += [
  # ─────────────────────────── SÁNDWICHES ───────────────────────────
  dict(id="sandwiches", cat="salado",
       es="Sándwiches bigotones", en="Bigote sandwiches",
       nota_es=None, nota_en=None,
       items=[
    ("Triple casero", "Homemade triple", "15",
     "Palta, huevo, tomate y mayonesa en pan ciabatta.",
     "Avocado, egg, tomato and mayo on ciabatta.", ["veg"]),
    ("Mixto grill", "Grilled mixto", "15",
     "Jamón, queso andino y mantequilla en pan ciabatta.",
     "Ham, Andean cheese and butter on ciabatta.", []),
    ("Capresse", "Caprese", "15",
     "Queso mozzarella, albahaca y tomate en pan chapla o ciabatta.",
     "Mozzarella, basil and tomato on chapla flatbread or ciabatta.", ["veg"]),
    ("Capresse power", "Caprese power", "17",
     "Queso mozzarella, tomate, albahaca, aceite de oliva y pollo deshilachado en pan chapla o ciabatta.",
     "Mozzarella, tomato, basil, olive oil and pulled chicken on chapla flatbread or ciabatta.", []),
    ("Tres jamones", "Three hams", "18",
     "Lomito ahumado, jamón inglés, bondiola, queso edam, tomate, lechuga y mayonesa en pan ciabatta.",
     "Smoked pork loin, English ham, pork shoulder, edam, tomato, lettuce and mayo on ciabatta.", []),
    ("Mediterráneo", "Mediterranean", "20",
     "Pollo a la plancha, queso mozzarella, champiñones, pimientos y salsa picantita en pan pita o ciabatta.",
     "Grilled chicken, mozzarella, mushrooms, peppers and a mildly spicy sauce on pita or ciabatta.", []),
    ("Pollo crispy", "Crispy chicken", "22",
     "Pechuga empanizada, queso cheddar, tocino, mayonesa Bigote, tomate y lechuga en pan brioche, con papas en hojuelas.",
     "Breaded chicken breast, cheddar, bacon, house Bigote mayo, tomato and lettuce on brioche, with crisps.", []),
    ("Mexicano", "Mexican", "17",
     "Pollo a la plancha, guacamole, queso cheddar y pimientos en pan pita o ciabatta.",
     "Grilled chicken, guacamole, cheddar and peppers on pita or ciabatta.", []),
    ("Pollo popeye", "Popeye chicken", "19",
     "Pollo a la plancha, espinaca, queso mozzarella, orégano y mayonesa Bigote en pan ciabatta.",
     "Grilled chicken, spinach, mozzarella, oregano and house Bigote mayo on ciabatta.", []),
    ("Caesar", "Caesar", "18",
     "Pollo a la plancha, salsa caesar, tocino, queso parmesano y lechuga en pan ciabatta o chapla.",
     "Grilled chicken, caesar dressing, bacon, parmesan and lettuce on ciabatta or chapla flatbread.", []),
    ("Pollo BBQ", "BBQ chicken", "22",
     "Pollo a la plancha, tocino, queso cheddar, salsa BBQ, tomate y lechuga en pan ciabatta.",
     "Grilled chicken, bacon, cheddar, BBQ sauce, tomato and lettuce on ciabatta.", []),
    ("Pollo palteado", "Chicken & avocado", "18",
     "Pollo deshilachado en mayonesa con palta, lechuga y tomate en pan ciabatta.",
     "Pulled chicken in mayo with avocado, lettuce and tomato on ciabatta.", []),
    ("Sándwich Romeo", "Romeo sandwich", "20",
     "Carne de hamburguesa con un toque de salsa napolitana, queso edam, tomate y lechuga en pan ciabatta.",
     "Burger patty with a touch of napolitana sauce, edam, tomato and lettuce on ciabatta.", []),
  ]),

  # ─────────────────────────── HAMBURGUESAS ───────────────────────────
  dict(id="hamburguesas", cat="salado",
       es="Hamburguesas", en="Burgers",
       nota_es="Todas se sirven con papas chips.", nota_en="All served with crisps.",
       items=[
    ("Clásica", "Classic", "19",
     "Hamburguesa de la casa, queso cheddar, tomate y lechuga + papas chips.",
     "House burger, cheddar, tomato and lettuce + crisps.", []),
    ("Royal", "Royal", "22",
     "Hamburguesa de la casa, queso edam, jamón, huevo frito, tomate y lechuga + papas chips.",
     "House burger, edam, ham, fried egg, tomato and lettuce + crisps.", []),
    ("Mexicana", "Mexican", "22",
     "Hamburguesa de la casa, guacamole, queso cheddar, tomate y lechuga + papas chips.",
     "House burger, guacamole, cheddar, tomato and lettuce + crisps.", []),
    ("BBQ", "BBQ", "23",
     "Hamburguesa de la casa, queso cheddar, salsa BBQ, tocino, tomate y lechuga + papas chips.",
     "House burger, cheddar, BBQ sauce, bacon, tomato and lettuce + crisps.", []),
    ("Anticuchera", "Anticuchera", "22",
     "Hamburguesa de la casa, queso edam, salsa anticuchera, champiñones, tomate y lechuga + papas chips.",
     "House burger, edam, anticuchera sauce, mushrooms, tomato and lettuce + crisps.", []),
  ]),

  # ─────────────────────────── WRAPS ───────────────────────────
  dict(id="wraps", cat="salado",
       es="Wraps", en="Wraps",
       nota_es=None, nota_en=None,
       items=[
    ("Wrap caesar", "Caesar wrap", "21",
     "Pollo deshilachado en salsa caesar, tocino, lechuga y queso parmesano.",
     "Pulled chicken in caesar dressing, bacon, lettuce and parmesan.", []),
    ("Wrap veggie", "Veggie wrap", "23",
     "Palta, champiñones salteados, queso, tomate, zanahoria y lechuga con salsa honey mustard.",
     "Avocado, sautéed mushrooms, cheese, tomato, carrot and lettuce with honey mustard.", ["veg"]),
    ("Wrap oriental", "Oriental wrap", "21",
     "Pollo empanizado, mix de nueces, pimiento, pepino, zanahoria, ajonjolí, lechuga y tomate con honey mustard.",
     "Breaded chicken, mixed nuts, pepper, cucumber, carrot, sesame, lettuce and tomato with honey mustard.", []),
    ("Wrap spicy chicken", "Spicy chicken wrap", "21",
     "Pollo deshilachado en salsa picante, queso cheddar, chips de papa, tomate y lechuga.",
     "Pulled chicken in spicy sauce, cheddar, potato crisps, tomato and lettuce.", []),
    ("Wrap palteado", "Chicken & avocado wrap", "24",
     "Pollo deshilachado en mayonesa, palta, tomate, queso y lechuga.",
     "Pulled chicken in mayo, avocado, tomato, cheese and lettuce.", []),
    ("Wrap anticuchero", "Anticuchero wrap", "21",
     "Pollo en cubos en salsa anticuchera, champiñones, queso, ajonjolí, lechuga y tomate.",
     "Diced chicken in anticuchera sauce, mushrooms, cheese, sesame, lettuce and tomato.", []),
    ("Wrap burger", "Burger wrap", "23",
     "Hamburguesa en trozos, guacamole, queso cheddar, tocino, tomate y lechuga.",
     "Chopped burger, guacamole, cheddar, bacon, tomato and lettuce.", []),
    ("Wrap thais", "Thai wrap", "23",
     "Pollo empanizado, queso, huevo duro, tocino, tomate y lechuga con salsa honey mustard.",
     "Breaded chicken, cheese, boiled egg, bacon, tomato and lettuce with honey mustard.", []),
    ("Wrap pollo BBQ", "BBQ chicken wrap", "24",
     "Pollo deshilachado en salsa BBQ, queso cheddar, tocino, tomate y lechuga.",
     "Pulled chicken in BBQ sauce, cheddar, bacon, tomato and lettuce.", []),
    ("Wrap club sándwich", "Club sandwich wrap", "26",
     "Pollo deshilachado en mayonesa, queso, tocino, jamón, palta, tomate y lechuga.",
     "Pulled chicken in mayo, cheese, bacon, ham, avocado, tomato and lettuce.", []),
  ]),

  # ─────────────────────────── ENSALADAS ───────────────────────────
  dict(id="ensaladas", cat="salado",
       es="Ensaladas", en="Salads",
       nota_es="Escoge un aliño: honey mustard, caesar, de la casa, aceite de oliva o anticuchero. "
               "Adicional de pollo 7 · adicional de palta 4.",
       nota_en="Choose a dressing: honey mustard, caesar, house, olive oil or anticuchero. "
               "Extra chicken 7 · extra avocado 4.",
       items=[
    ("Caesar", "Caesar", "24",
     "Mix de lechugas, tocino, pollo a la plancha, croutones y queso parmesano.",
     "Mixed leaves, bacon, grilled chicken, croutons and parmesan.", []),
    ("Thais", "Thai", "25",
     "Mix de lechugas, tomate, queso, tocino, tortillas chips, pollo empanizado y huevo duro.",
     "Mixed leaves, tomato, cheese, bacon, tortilla chips, breaded chicken and boiled egg.", []),
    ("Balana", "Balana", "24",
     "Mix de lechugas y espinaca, pechuga a la plancha, tocino, manzanas y mix de nueces.",
     "Mixed leaves and spinach, grilled chicken breast, bacon, apple and mixed nuts.", []),
    ("Cobb", "Cobb", "28",
     "Mix de lechugas, tomate, palta, tocino, pollo en cubos, queso y huevo duro.",
     "Mixed leaves, tomato, avocado, bacon, diced chicken, cheese and boiled egg.", []),
    ("Campestre", "Campestre", "24",
     "Mix de lechugas y espinaca, pechuga a la plancha, palta, pepino, tomate y zanahoria.",
     "Mixed leaves and spinach, grilled chicken breast, avocado, cucumber, tomato and carrot.", []),
    ("Pastor", "Pastor", "30",
     "Mix de lechugas y espinaca, pimiento, tomate, zanahoria, palta y dos pechugas de pollo.",
     "Mixed leaves and spinach, pepper, tomato, carrot, avocado and two chicken breasts.", []),
    ("Oriental", "Oriental", "24",
     "Mix de lechugas y espinaca, pollo empanizado, pimiento, zanahoria, pepino, tortillas chips, ajonjolí, "
     "gajos de naranja y mix de nueces.",
     "Mixed leaves and spinach, breaded chicken, pepper, carrot, cucumber, tortilla chips, sesame, "
     "orange segments and mixed nuts.", []),
  ]),

  # ─────────────────────────── PASTAS ───────────────────────────
  dict(id="pastas", cat="salado",
       es="Pastas", en="Pasta",
       nota_es="Extras: queso parmesano 3 · tocino 4 · pollo 7 · hamburguesa 9. "
               "La milanesa napolitana es una pechuga empanizada con salsa de tomate y queso mozzarella.",
       nota_en="Extras: parmesan 3 · bacon 4 · chicken 7 · burger 9. "
               "Milanesa napolitana is a breaded chicken breast with tomato sauce and mozzarella.",
       items=[
    ("A lo Alfredo", "Alfredo", "22",
     "Macarrones con salsa blanca y jamón.",
     "Macaroni in white sauce with ham.", []),
    ("Champipollo", "Champipollo", "24",
     "Macarrones con salsa blanca, pollo en cubos, champiñones, queso y especias.",
     "Macaroni in white sauce with diced chicken, mushrooms, cheese and spices.", []),
    ("Mac and cheese", "Mac and cheese", "22",
     "Macarrones con queso mozzarella, cheddar y andino, crema de leche y especias.",
     "Macaroni with mozzarella, cheddar and Andean cheese, cream and spices.", ["veg"]),
    ("Pasta caesar (fría)", "Caesar pasta (cold)", "24",
     "Macarrones con salsa caesar, lechuga en tiras, tocino, queso parmesano y pechuga empanizada.",
     "Macaroni in caesar dressing with shredded lettuce, bacon, parmesan and breaded chicken.", []),
    ("Pasta mediterránea", "Mediterranean pasta", "24",
     "Macarrones con salsa de tomate, queso mozzarella, albahaca, champiñones y pollo en cubos.",
     "Macaroni in tomato sauce with mozzarella, basil, mushrooms and diced chicken.", []),
    ("Pasta bianca", "Pasta bianca", "26",
     "Macarrones con salsa blanca, acompañados de milanesa a la napolitana.",
     "Macaroni in white sauce, served with milanesa napolitana.", []),
    ("Pasta napolitana", "Pasta napolitana", "26",
     "Macarrones con salsa de tomate, acompañados de milanesa a la napolitana.",
     "Macaroni in tomato sauce, served with milanesa napolitana.", []),
  ]),

  # ─────────────────────────── PIQUEOS ───────────────────────────
  dict(id="piqueos", cat="salado dulce",
       es="Piqueos para compartir", en="Sharing plates",
       nota_es=None, nota_en=None,
       items=[
    ("Quesadillas de queso", "Cheese quesadillas", "26",
     "Quesadillas rellenas de queso mozzarella y cheddar, acompañadas con guacamole. "
     "Añade pollo 5 · tocino 4 · guacamole 4.",
     "Quesadillas filled with mozzarella and cheddar, served with guacamole. "
     "Add chicken 5 · bacon 4 · guacamole 4.", ["veg"]),
    ("Queso frito", "Fried cheese", "23",
     "8 triángulos de queso cajamarquino fritos. Añade guacamole 4.",
     "8 fried triangles of Cajamarca cheese. Add guacamole 4.", ["veg"]),
    ("Dedos de pollo con yucas fritas", "Chicken fingers with fried cassava", "32",
     "8 dedos de pollo acompañados con yucas fritas y salsas.",
     "8 chicken fingers with fried cassava and dipping sauces.", []),
    ("Yucas fritas", "Fried cassava", "18",
     "Yucas fritas acompañadas con salsas de la casa.",
     "Fried cassava with house sauces.", ["veg"]),
    ("Piqueo Bigote", "Bigote sharing platter", "28",
     "Waffle bites, fresas, plátanos, malvaviscos y brownie bites acompañados con salsa de chocolate.",
     "Waffle bites, strawberries, banana, marshmallows and brownie bites with chocolate sauce.", ["veg", "top"]),
  ]),
]

CATEGORIAS += [
  # ─────────────────────────── CAFÉ ───────────────────────────
  dict(id="cafe", cat="bebidas cafe",
       es="Café", en="Coffee",
       nota_es="Precios de 8 oz a 12 oz donde se indican dos cifras. "
               "Adicionales: shot de leche 2 · shot de café 3 · leche de almendras +3 · taza de leche +5.",
       nota_en="Two figures means 8 oz to 12 oz. "
               "Extras: milk shot 2 · coffee shot 3 · almond milk +3 · cup of milk +5.",
       items=[
    ("Espresso", "Espresso", "5.5", None, None, []),
    ("Espresso doble", "Double espresso", "7.5", None, None, []),
    ("Cortadito", "Cortado", "7.5", None, None, []),
    ("Americano", "Americano", "6.5 – 8.5", None, None, []),
    ("Cappuccino", "Cappuccino", "8 – 11", None, None, []),
    ("Cappuccino de naranja", "Orange cappuccino", "11 – 14", None, None, []),
    ("Mocaccino", "Mocaccino", "11", None, None, []),
    ("Latte", "Latte", "9.5", None, None, []),
    ("Prensa francesa", "French press", "9", None, None, []),
    ("Flat white", "Flat white", "9", None, None, []),
    ("Nuteccino", "Nuteccino", "16",
     "Cappuccino de crema de avellanas.", "Hazelnut cream cappuccino.", []),
    ("Latte encanelado", "Cinnamon latte", "13",
     "Café con glaseado de vainilla, salsa de canela, crumble y chantilly.",
     "Coffee with vanilla glaze, cinnamon sauce, crumble and whipped cream.", ["top"]),
    ("Café helado", "Iced coffee", "10", None, None, []),
    ("Café helado y naranja", "Iced coffee & orange", "12", None, None, []),
    ("Café helado y maracuyá", "Iced coffee & passion fruit", "12", None, None, []),
    ("Latte helado", "Iced latte", "11", None, None, []),
    ("Moka helado", "Iced mocha", "14", None, None, []),
    ("Latte encanelado helado", "Iced cinnamon latte", "15",
     "Café con glaseado de vainilla, salsa de canela, crumble y chantilly.",
     "Coffee with vanilla glaze, cinnamon sauce, crumble and whipped cream.", []),
    ("Affogato", "Affogato", "13", None, None, []),
    ("Affogato de lúcuma", "Lúcuma affogato", "13", None, None, []),
    ("Affogato de matcha", "Matcha affogato", "13", None, None, []),
    ("Frappé de café", "Coffee frappé", "14", None, None, []),
    ("Frappé de chocolate", "Chocolate frappé", "17", None, None, []),
    ("Frappé de oreo", "Oreo frappé", "17", None, None, []),
  ]),

  # ─────────────────────────── CHOCOLATE ───────────────────────────
  dict(id="chocolate", cat="bebidas dulce",
       es="Chocolate caliente", en="Hot chocolate",
       nota_es=None, nota_en=None,
       items=[
    ("Chocolate caliente", "Hot chocolate", "11", None, None, []),
    ("Chocolate Bigote", "Bigote hot chocolate", "14",
     "Chocolate caliente, malvaviscos y crema chantilly.",
     "Hot chocolate, marshmallows and whipped cream.", []),
    ("Chocobrownie", "Chocobrownie", "17",
     "Chocolate caliente, brownie, leche condensada y crema chantilly.",
     "Hot chocolate, brownie, condensed milk and whipped cream.", []),
  ]),

  # ─────────────────────────── BEBIDAS FRÍAS ───────────────────────────
  dict(id="bebidas", cat="bebidas",
       es="Jugos, frozens y limonadas", en="Juices, frozens & lemonades",
       nota_es="Frutas a escoger: mango, piña, papaya, plátano, aguaymanto, maracuyá, fresa y naranja (+2). "
               "Combinaciones recomendadas: fresa, piña y papaya · mango, piña y limón · mango y maracuyá · "
               "mango, fresa y naranja · fresa y plátano.",
       nota_en="Choose from: mango, pineapple, papaya, banana, goldenberry, passion fruit, strawberry and orange (+2). "
               "House combinations: strawberry, pineapple & papaya · mango, pineapple & lime · mango & passion fruit · "
               "mango, strawberry & orange · strawberry & banana.",
       items=[
    ("Jugo de 1 fruta", "Single fruit juice", "12", "Con leche +2.", "With milk +2.", []),
    ("Jugo de 2 frutas", "Two fruit juice", "14", "Con leche +2.", "With milk +2.", []),
    ("Jugo de 3 frutas", "Three fruit juice", "16", "Con leche +2.", "With milk +2.", []),
    ("Frozen de piña, naranja y menta", "Pineapple, orange & mint frozen", "14", None, None, []),
    ("Frozen de naranja y piña", "Orange & pineapple frozen", "14", None, None, []),
    ("Frozen de maracuyá y mango", "Passion fruit & mango frozen", "14", None, None, ["top"]),
    ("Frozen de fresa y maracuyá", "Strawberry & passion fruit frozen", "14", None, None, []),
    ("Frozen de una fruta", "Single fruit frozen", "13", None, None, []),
    ("Limonada", "Lemonade", "8", None, None, []),
    ("Limonada con menta", "Mint lemonade", "9", None, None, []),
    ("Limonada con hierba luisa", "Lemon verbena lemonade", "9", None, None, []),
    ("Limonada con hierba buena", "Spearmint lemonade", "9", None, None, []),
    ("Limonada con fresa", "Strawberry lemonade", "10", None, None, []),
    ("Limonada frozen", "Frozen lemonade", "10", None, None, []),
    ("Limonada con flor de Jamaica y hierba buena", "Hibiscus & spearmint lemonade", "14", None, None, []),
    ("Limonada con frutos rojos", "Red berry lemonade", "14", None, None, []),
    ("Limonada cítrica", "Citrus lemonade", "15",
     "Zumo de limón, flor de Jamaica, naranja y hielo.",
     "Lime juice, hibiscus, orange and ice.", []),
    ("Flor de Jamaica, menta y fresas", "Hibiscus, mint & strawberry", "12", None, None, []),
    ("Soda de arándanos", "Blueberry soda", "12", None, None, []),
    ("Piña y hierba luisa", "Pineapple & lemon verbena", "13", None, None, []),
    ("Té helado", "Iced tea", "8", None, None, []),
    ("Té helado de naranja", "Orange iced tea", "8", None, None, []),
    ("Agua mineral", "Sparkling water", "5", None, None, []),
  ]),

  # ─────────────────────────── INFUSIONES ───────────────────────────
  dict(id="infusiones", cat="bebidas",
       es="Infusiones", en="Herbal teas",
       nota_es="Las infusiones servidas con frutas y hierbas cuestan 9. "
               "Los filtrantes de la casa: taza 9 · heladas 11.",
       nota_en="Infusions served with fruit and herbs are 9. "
               "House blends: cup 9 · iced 11.",
       items=[
    ("Bigote", "Bigote", "9",
     "Hierba buena, hierba luisa, manzanilla, canela, miel, aguaymanto, fresa y manzana.",
     "Spearmint, lemon verbena, chamomile, cinnamon, honey, goldenberry, strawberry and apple.", ["top"]),
    ("Cítrica", "Citrus", "9",
     "Té negro, menta, piña, aguaymanto, miel, canela y limón.",
     "Black tea, mint, pineapple, goldenberry, honey, cinnamon and lime.", []),
    ("Berries", "Berries", "9",
     "Menta, hierba buena, miel, fresa, arándano y aguaymanto.",
     "Mint, spearmint, honey, strawberry, blueberry and goldenberry.", []),
    ("Frutal", "Fruity", "9",
     "Manzanilla, canela, miel, naranja, piña, aguaymanto y manzana deshidratada.",
     "Chamomile, cinnamon, honey, orange, pineapple, goldenberry and dried apple.", []),
    ("Del bosque", "Forest", "9",
     "Flor de Jamaica, anís estrella, manzanas y fresas deshidratadas, miel de abeja, arándanos y canela.",
     "Hibiscus, star anise, dried apple and strawberry, honey, blueberries and cinnamon.", []),
    ("De piña", "Pineapple", "9",
     "Infusión de piña, canela, clavo de olor, hierba luisa, manzanilla, limón y miel de abeja.",
     "Pineapple, cinnamon, clove, lemon verbena, chamomile, lime and honey.", []),
    ("De maracuyá", "Passion fruit", "9",
     "Infusión de maracuyá, hierba luisa, manzanilla, miel de abeja y canela.",
     "Passion fruit, lemon verbena, chamomile, honey and cinnamon.", []),
    ("De naranja", "Orange", "9",
     "Infusión de naranja, menta, canela en rama, cardamomo y miel de abeja.",
     "Orange, mint, cinnamon stick, cardamom and honey.", []),
    ("Infusión de los Andes", "Andean blend", "9 – 11",
     "Té verde, menta, muña y cáscara de naranja.",
     "Green tea, mint, muña and orange peel.", []),
    ("Infusión morada", "Purple blend", "9 – 11",
     "Flor de Jamaica, maíz morado, piña y pasas.",
     "Hibiscus, purple corn, pineapple and raisins.", []),
    ("Manzana tropical", "Tropical apple", "9 – 11",
     "Té verde, flor de Jamaica, canela y manzana.",
     "Green tea, hibiscus, cinnamon and apple.", []),
    ("Flor cítrica", "Citrus flower", "9 – 11",
     "Flor de Jamaica, cáscaras de limón con naranja y menta.",
     "Hibiscus, lime and orange peel with mint.", []),
    ("Matcha latte", "Matcha latte", "9 – 11",
     "Té verde pulverizado y leche.", "Powdered green tea and milk.", []),
    ("Chai latte", "Chai latte", "9 – 11",
     "Indian chai y leche.", "Indian chai and milk.", []),
    ("Indian chai", "Indian chai", "9 – 11",
     "Té negro, cardamomo, jengibre, pimienta rosada, clavo de olor y canela.",
     "Black tea, cardamom, ginger, pink pepper, clove and cinnamon.", []),
  ]),

  # ─────────────────────────── MILKSHAKES ───────────────────────────
  dict(id="milkshakes", cat="bebidas dulce",
       es="Milkshakes", en="Milkshakes",
       nota_es=None, nota_en=None,
       items=[
    ("Vainilla", "Vanilla", "17", None, None, []),
    ("Chocolate", "Chocolate", "17", None, None, []),
    ("Fresa", "Strawberry", "17", None, None, []),
    ("Lúcuma", "Lúcuma", "17", None, None, []),
    ("Vainilla latte", "Vanilla latte", "20",
     "Helado de vainilla y café con crema chantilly.",
     "Vanilla ice cream and coffee with whipped cream.", []),
    ("Frutos rojos", "Red berries", "20",
     "Helado de vainilla y mermelada de frutos rojos con crema chantilly.",
     "Vanilla ice cream and red berry jam with whipped cream.", []),
    ("Brownie", "Brownie", "20",
     "Helado de chocolate y vainilla licuado con brownie, acompañado de crema chantilly.",
     "Chocolate and vanilla ice cream blended with brownie, with whipped cream.", []),
    ("Oreo", "Oreo", "20",
     "Helado de oreo, chocolate, galleta oreo y vainilla.",
     "Oreo ice cream, chocolate, oreo biscuit and vanilla.", []),
  ]),
]
